version: '3'

services:
  app:
    build: .
    command: sleep inf
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d/:/etc/sudoers.d/:ro
      - /home/:/home/
    working_dir: "${PWD}"
    user: 1006:10
    group_add:
      - wheel
